// package-vue/src/Subscription.vue
<template></template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount, defineProps, watch } from 'vue';
import { useQueryClient } from '@tanstack/vue-query';
import { formatData } from './formatData';

const props = defineProps({
  contentConnected: Boolean,
});

const queryClient = useQueryClient();
const queryCache = queryClient.getQueryCache();
const contentMessageQueue: any = [];

const sendEvent = (data: any) => {
  window.postMessage(
    {
      framework: 'vue',
      type: 'event',
      payload: data,
    },
    '*'
  );
};

const handleQueryCacheChange = async (event: any) => {
  const message = formatData(event, queryClient);

  if (!message) return;
  if (!props.contentConnected) {
    contentMessageQueue.push(message);
  } else {
    sendEvent(message);
  }
};

watch(
  () => props.contentConnected,
  newVal => {
    if (newVal) {
      contentMessageQueue.forEach((message: any) => {
        sendEvent(message);
      });
      contentMessageQueue.length = 0;
    }
  }
);

onMounted(() => {
  const unsubscribe = queryCache.subscribe(handleQueryCacheChange);
  onBeforeUnmount(() => unsubscribe());
});
</script>

<style scoped></style>

// package/examples/example-2-react/client/src/client/link/Subscription.tsx
import React, { useEffect, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { formatData } from './formatData';

type SubscriptionProps = {
  contentConnected: boolean;
};

function Subscription({ contentConnected }: SubscriptionProps) {
  const queryClient = useQueryClient();
  const queryCache = queryClient.getQueryCache();
  const [contentMessageQueue, setContentMessageQueue] = useState<any[]>([]);

  const sendEvent = (data: any) => {
    window.postMessage(
      {
        framework: 'react',
        type: 'event',
        payload: data,
      },
      '*'
    );
  };

  const handleQueryCacheChange = async (event: any) => {
    const message = await formatData(event, queryClient);
    if (!message) return;
    if (!contentConnected) {
      setContentMessageQueue(prevQueue => [...prevQueue, message]);
    } else {
      sendEvent(message);
    }
  };

  useEffect(() => {
    if (contentConnected) {
      contentMessageQueue.forEach(sendEvent);
      setContentMessageQueue([]);
    }
  }, [contentConnected, contentMessageQueue]);

  useEffect(() => {
    const unsubscribe = queryCache.subscribe(handleQueryCacheChange);
    return () => unsubscribe();
  }, []);

  return <div>Subscription Component</div>;
}

export default Subscription;
