// package - vue/examples/example-3-vue/client/src/link/index.vue
<template>
  <TimeTravel v-if="timeTravel" />
  <Subscription v-else :content-connected="contentConnected" />
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import Subscription from './Subscription.vue';
import TimeTravel from './TimeTravel.vue';

const timeTravel = ref(false);
const contentConnected = ref(false);

const handleContentMessages = (message: any) => {
  if (message.data?.type === 'content-script-ready') {
    console.log('APP: Connected to content.ts');
    contentConnected.value = true;
    window.postMessage({ type: 'app-connected' }, '*');
  }

  if (message.data?.type === 'time-travel') {
    timeTravel.value = message.detail;
  }
};

onMounted(() => {
  console.log('APP: Mounting Event Listeners');
  window.addEventListener('message', handleContentMessages);
});

onBeforeUnmount(() => {
  window.removeEventListener('message', handleContentMessages);
});
</script>

<script lang="ts">
export default {
  name: 'VueQueryRewind',
};
</script>

<style scoped></style>

// package-react/example/client/src/link/index.tsx
import React, { useEffect, useRef, useState } from 'react';
import Subscription from './Subscription';
import TimeTravel from './TimeTravel';

function ReactQueryRewind() {
  const [timeTravel, setTimeTravel] = useState(false);
  const contentConnectedRef = useRef(false);
  const contentMessageQueueRef = useRef<any[]>([]);

  const sendContentMessageQueue = () => {
    contentMessageQueueRef.current.forEach(sendEvent);
    contentMessageQueueRef.current = [];
  };

  const handleMessages = (message: any) => {
    if (contentConnectedRef.current) {
      sendEvent(message);
    } else {
      contentMessageQueueRef.current.push(message);
    }
  };

  const sendEvent = (event: any) => {
    window.postMessage(
      { framework: 'react', type: 'event', payload: event },
      '*'
    );
  };

  const handleContentMessages = (message: MessageEvent) => {
    if (message.data?.type === 'content-script-ready') {
      // console.log('APP: Content.ts connected');
      contentConnectedRef.current = true;
      window.postMessage({ type: 'app-connected' }, '*');
      sendContentMessageQueue();
    }

    if (message.data?.type === 'time-travel') {
      setTimeTravel(message.data.payload);
    }
  };

  useEffect(() => {
    // console.log('APP: Mounting Event Listeners');
    window.addEventListener('message', handleContentMessages);

    return () => {
      window.removeEventListener('message', handleContentMessages);
    };
  }, []);

  useEffect(() => {
    // console.log('timeTravel', timeTravel);
  }, [timeTravel]);

  return (
    <div>
      {timeTravel ? (
        <TimeTravel />
      ) : (
        <Subscription handleMessages={handleMessages} />
      )}
    </div>
  );
}

export default ReactQueryRewind;
