// package-vue/example/client/src/App.vue
<template>
  <VueQueryRewind />

  <div class="window">
    <div class="nav-bar">
      <span class="title">Vue Query Rewind</span>
      <div class="nav-options">
        <div
          :class="{ 'nav-option': true, active: screenView === 'Feed One' }"
          @click="handleNavClick('Feed One')"
        >
          Feed 1
        </div>
        <div
          :class="{ 'nav-option': true, active: screenView === 'Feed Two' }"
          @click="handleNavClick('Feed Two')"
        >
          Feed 2
        </div>
        <div
          :class="{ 'nav-option': true, active: screenView === 'Feed Three' }"
          @click="handleNavClick('Feed Three')"
        >
          Feed 3
        </div>
      </div>
    </div>

    <component :is="currentScreenComponent"></component>
  </div>
</template>

<script setup lang="ts">
import { VueQueryRewind } from '@react-query-rewind/vue-query-rewind';

import { ref, computed } from 'vue';
import PostsOne from './components/PostsOne.vue';
import PostsTwo from './components/PostsTwo.vue';
import PostsThree from './components/PostsThree.vue';

const screenView = ref('Feed One');

const handleNavClick = (screenName: string) => {
  screenView.value = screenName;
};

const currentScreenComponent = computed(() => {
  switch (screenView.value) {
    case 'Feed One':
      return PostsOne;
    case 'Feed Two':
      return PostsTwo;
    case 'Feed Three':
      return PostsThree;
    default:
      return null;
  }
});
</script>

<style scoped></style>

// examples/example-2/client/src/client/App.tsx
import React, { useState } from 'react';
import PostsOne from './components/PostsOne';
import PostsTwo from './components/PostsTwo';
import PostsThree from './components/PostsThree';

const App = () => {
  const [screenView, setScreenView] = useState<string>('Posts One');

  const handleNavClick = (screenName: string) => {
    setScreenView(screenName);
  };

  return (
    <>
      <div className="window">
        <div className="nav-bar">
          <span className="title">React Query Rewind</span>
          <div className="nav-options">
            <div
              className={`nav-option ${
                screenView === 'Posts One' ? 'active' : ''
              }`}
              onClick={() => handleNavClick('Posts One')}
            >
              Feed 1
            </div>
            <div
              className={`nav-option ${
                screenView === 'Posts Two' ? 'active' : ''
              }`}
              onClick={() => handleNavClick('Posts Two')}
            >
              Feed 2
            </div>
            <div
              className={`nav-option ${
                screenView === 'Posts Three' ? 'active' : ''
              }`}
              onClick={() => handleNavClick('Posts Three')}
            >
              Feed 3
            </div>
          </div>
        </div>

        {screenView === 'Posts One' && <PostsOne />}
        {screenView === 'Posts Two' && <PostsTwo />}
        {screenView === 'Posts Three' && <PostsThree />}
      </div>
    </>
  );
};

export default App;
