// package/examples/example-3/client/src/link/TimeTravel.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount } from 'vue';
import { useQueryClient } from '@tanstack/vue-query';
// import { QueryDisplay } from './types';

export type QueryDisplay = {
  queryKey: string;
  queryData: any;
};

const queryClient = useQueryClient();

onMounted(() => {
  console.log('TIME TRAVEL MOUNTED');

  const updateUi = (event: any) => {
    const currentQuery: QueryDisplay[] = event.detail;
    currentQuery.forEach(queryState => {
      if (queryState.queryData !== '') {
        queryClient.setQueryData(
          [queryState.queryKey.slice(2, -2)],
          queryState.queryData
        );
      }
    });
  };
  window.addEventListener('update-ui', updateUi);

  onBeforeUnmount(() => {
    window.removeEventListener('update-ui', updateUi);
  });
});
</script>

// package-svelte/example/client/src/link/TimeTravel.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { QueryDisplay } from "./types";
  import { useQueryClient } from "@tanstack/svelte-query";

  const queryClient = useQueryClient();

  onMount(() => {
    // console.log("TIME TRAVEL MOUNTED");

    const updateUi = (event: any) => {
      const currentQuery: QueryDisplay[] = event.detail;
      currentQuery.forEach((queryState) => {
        if (queryState.queryData !== "") {
          queryClient.setQueryData(
            [queryState.queryKey.slice(2, -2)],
            queryState.queryData,
          );
        }
      });
    };

    window.addEventListener("update-ui", updateUi);

    return () => {
      window.removeEventListener("update-ui", updateUi);
    };
  });
</script>
