// package/examples/example-2-react/client/src/client/link/index.tsx
import React, { useEffect, useState } from 'react';
import Subscription from './Subscription';
import TimeTravel from './TimeTravel';

function ReactQueryRewind() {
  const [timeTravel, setTimeTravel] = useState(false);
  const [contentConnected, setContentConnected] = useState(false);

  const handleContentMessages = (message: MessageEvent) => {
    if (message.data?.type === 'content-script-ready') {
      console.log('APP: Connected to content.ts');
      setContentConnected(true);
      window.postMessage({ type: 'app-connected' }, '*');
    }

    if (message.data?.type === 'time-travel') {
      setTimeTravel(message.data.detail);
    }
  };

  useEffect(() => {
    window.addEventListener('message', handleContentMessages);

    return () => {
      window.removeEventListener('message', handleContentMessages);
    };
  }, []);

  return (
    <div>
      {timeTravel ? (
        <TimeTravel />
      ) : (
        <Subscription contentConnected={contentConnected} />
      )}
    </div>
  );
}

export default ReactQueryRewind;

// package/examples/example-3/client/src/link/index.vue
<template>
  <TimeTravel v-if="timeTravel" />
  <Subscription v-else :content-connected="contentConnected" />
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import Subscription from './Subscription.vue';
import TimeTravel from './TimeTravel.vue';

const timeTravel = ref(false);
const contentConnected = ref(false);

const handleContentMessages = (message: any) => {
  if (message.data?.type === 'content-script-ready') {
    console.log('APP: Content.ts Connected');
    contentConnected.value = true;
    window.postMessage({ type: 'app-connected' }, '*');
  }

  if (message.data?.type === 'time-travel') {
    timeTravel.value = message.detail;
  }
};

onMounted(() => {
  window.addEventListener('message', handleContentMessages);
});

onBeforeUnmount(() => {
  window.removeEventListener('message', handleContentMessages);
});
</script>

<script lang="ts">
export default {
  name: 'VueQueryRewind',
};
</script>

<style scoped></style>
