// package/examples/example-4/client/src/link/Subscription.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import formatData from "./formatData";
  import { useQueryClient } from "@tanstack/svelte-query";

  const queryClient = useQueryClient();
  const queryCache = queryClient.getQueryCache();

  onMount(() => {
    const handleQueryCacheChange = async (event: any) => {
      await new Promise<void>((resolve) => setTimeout(resolve, 250));

      const data = formatData(event, queryClient);
      if (data) {
        window.postMessage(
          {
            framework: "svelte",
            type: "event",
            payload: data,
          },
          "*",
        );
      }
    };

    const unsubscribe = queryCache.subscribe(handleQueryCacheChange);

    return () => {
      unsubscribe();
    };
  });
</script>

// package/examples/example-3/client/src/link/Subscription.vue
<template></template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount } from 'vue';
import { useQueryClient } from '@tanstack/vue-query';
import { formatData } from './formatData';

onMounted(() => {
  const queryClient = useQueryClient();
  const queryCache = queryClient.getQueryCache();
  let initialMessageSent = false;

  const handleQueryCacheChange = async (event: any) => {
    if (!initialMessageSent) {
      await new Promise(resolve => setTimeout(resolve, 250));
      initialMessageSent = true;
    }

    const data = formatData(event, queryClient);

    if (data) {
      window.postMessage(
        {
          framework: 'vue',
          type: 'event',
          payload: data,
        },
        '*'
      );
    }
  };

  const unsubscribe = queryCache.subscribe(handleQueryCacheChange);

  onBeforeUnmount(() => unsubscribe());
});
</script>

<style scoped></style>
