// package-react/src/Subscription.tsx
import React, { useEffect } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { formatData } from './formatData';

type SubscriptionProps = {
  handleMessages: any;
};

function Subscription({ handleMessages }: SubscriptionProps) {
  const queryClient = useQueryClient();
  const queryCache = queryClient.getQueryCache();

  const handleQueryCacheChange = async (event: any) => {
    const message = formatData(event, queryClient);
    if (message) handleMessages(message);
  };

  useEffect(() => {
    const unsubscribe = queryCache.subscribe(handleQueryCacheChange);
    return () => unsubscribe();
  }, []);

  return <></>;
}

export default Subscription;

// package/examples/example-3/client/src/link/Subscription.vue
<script>
import { onMounted, onBeforeUnmount } from 'vue';
import { useQueryClient } from '@tanstack/vue-query';
import { formatData } from './formatData';

export default {
  name: 'Subscription',
  setup() {
    const queryClient = useQueryClient();
    const queryCache = queryClient.getQueryCache();

    const handleQueryCacheChange = event => {
      const data = formatData(event, queryClient);
      if (data) {
        window.postMessage(
          {
            type: 'react-query-rewind',
            payload: data,
          },
          '*'
        );
      }
    };

    onMounted(() => {
      const unsubscribe = queryCache.subscribe(handleQueryCacheChange);
      return () => unsubscribe();
    });

    return {};
  },
};
</script>
