// examples/example-2/client/src/client/linked/TimeTravel.tsx
import React, { useEffect } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { QueryDisplay } from '../types';

const TimeTravel = () => {
  const queryClient = useQueryClient();

  useEffect(() => {
    const listener = (event: CustomEvent) => {
      const currentQuery: QueryDisplay[] = event.detail.currentQuery;
      currentQuery.forEach((queryState) => {
        if (queryState.queryData !== '') {
          queryClient.setQueryData(
            [queryState.queryKey.slice(2, -2)],
            queryState.queryData
          );
        }
      });
    };
    window.addEventListener('UpdateUI', listener);
    return () => window.removeEventListener('UpdateUI', listener);
  }, []);

  return <></>;
};

export default TimeTravel;

// package/examples/example-3/client/src/link/TimeTravel.vue
<script>
import { onMounted, onBeforeUnmount } from 'vue';
import { useQueryClient } from '@tanstack/vue-query';

export default {
  name: 'TimeTravel',
  setup() {
    const queryClient = useQueryClient();

    onMounted(() => {
      const listener = event => {
        const currentQuery = event.detail.currentQuery;
        currentQuery.forEach(queryState => {
          if (queryState.queryData !== '') {
            queryClient.setQueryData(
              [queryState.queryKey.slice(2, -2)],
              queryState.queryData
            );
          }
        });
      };
      window.addEventListener('UpdateUI', listener);

      onBeforeUnmount(() => {
        window.removeEventListener('UpdateUI', listener);
      });
    });

    return {};
  },
};
</script>
