// package-react/example/client/src/link/TimeTravel.tsx
import React, { useEffect } from 'react';
import { useQueryClient } from '@tanstack/react-query';

export type QueryDisplay = {
  queryKey: string;
  queryData: any;
};

function TimeTravel() {
  const queryClient = useQueryClient();

  const handleUpdateUi = (message: MessageEvent) => {
    if (message.data?.type === 'update-ui') {
      const currentQuery: QueryDisplay[] = message.data.payload;
      currentQuery.forEach(queryState => {
        if (queryState.queryData !== '') {
          queryClient.setQueryData(
            [queryState.queryKey.slice(2, -2)],
            queryState.queryData
          );
        }
      });
    }
  };

  useEffect(() => {
    window.addEventListener('message', handleUpdateUi);

    return () => {
      window.removeEventListener('message', handleUpdateUi);
    };
  }, []);

  return <></>;
}

export default TimeTravel;

// package/examples/example-3-vue/client/src/link/TimeTravel.vue
<template></template>

<script setup lang="ts">
import { onMounted, onBeforeUnmount } from 'vue';
import { useQueryClient } from '@tanstack/vue-query';
// import { QueryDisplay } from './types';

export type QueryDisplay = {
  queryKey: string;
  queryData: any;
};

const queryClient = useQueryClient();

const handleUpdateUi = (message: any) => {
  if (message.data?.type === 'update-ui') {
    const currentQuery: QueryDisplay[] = message.detail;
    currentQuery.forEach(queryState => {
      if (queryState.queryData !== '') {
        queryClient.setQueryData(
          [queryState.queryKey.slice(2, -2)],
          queryState.queryData
        );
      }
    });
  }
};

onMounted(() => {
  window.addEventListener('message', handleUpdateUi);
});

onBeforeUnmount(() => {
  window.removeEventListener('message', handleUpdateUi);
});
</script>

<style scoped></style>
